 FROM amazoncorretto:8-alpine-jdk
ARG REPO_BRANCH=${REPO_BRANCH}

RUN apk update

RUN apk add git

WORKDIR /app

RUN git clone --branch ${REPO_BRANCH} https://github.com/JuezLTI/questions-storage.git

WORKDIR /app/questions-storage

RUN chmod +x mvnw

EXPOSE 8080

ENTRYPOINT [ "./mvnw", "spring-boot:run" ]
