FROM eclipse-temurin:21-jdk-jammy

ARG JAVA_VALIDATOR_BRANCH=${JAVA_VALIDATOR_BRANCH}
ARG NODE_VERSION=${NODE_VERSION}

RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3 \
    php \
    && rm -rf /var/lib/apt/lists/*

ENV NVM_DIR=/root/.nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
    && . "$NVM_DIR/nvm.sh" \
    && nvm install ${NODE_VERSION} \
    && nvm use ${NODE_VERSION} \
    && nvm alias default ${NODE_VERSION}

ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"

WORKDIR /app

RUN git clone --branch ${JAVA_VALIDATOR_BRANCH} https://github.com/JuezLTI/java-evaluator.git

WORKDIR /app/java-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "prod" ]
