FROM node:24

ARG MONGO_VALIDATOR_BRANCH=${MONGO_VALIDATOR_BRANCH}

RUN npm install -g nodemon

WORKDIR /app


RUN apt-get update && apt-get install -y \
    curl \
    git

RUN wget https://downloads.mongodb.com/compass/mongodb-mongosh_2.5.8_amd64.deb
RUN dpkg -i mongodb-mongosh_2.5.8_amd64.deb
RUN wget https://repo.mongodb.org/apt/debian/dists/bookworm/mongodb-org/8.2/main/binary-amd64/mongodb-org-server_8.2.1_amd64.deb
RUN dpkg -i mongodb-org-server_8.2.1_amd64.deb

# Copia el script de entrada de Docker para iniciar MongoDB y luego ejecutar el comando proporcionado
COPY docker-mongo-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
RUN mkdir -p /app/mongodb
RUN chmod -R 700 /app/mongodb

RUN git clone --branch ${MONGO_VALIDATOR_BRANCH} https://github.com/JuezLTI/mongodb-evaluator.git

RUN mkdir -p /app/mongodb-evaluator/server/public/zip

WORKDIR /app/mongodb-evaluator/server

RUN npm ci
# RUN npm install

EXPOSE 3000

ENTRYPOINT [ "docker-entrypoint.sh" ]
