FROM node:24-alpine3.21
ARG XML_VALIDATOR_BRANCH=${XML_VALIDATOR_BRANCH}

RUN apk update && apk add git 

WORKDIR /app

RUN git clone --branch ${XML_VALIDATOR_BRANCH} https://github.com/JuezLTI/xml-evaluator.git

WORKDIR /app/xml-evaluator/server

RUN npm ci

EXPOSE 3000

ENTRYPOINT [ "npm", "run", "prod" ]
